# Generated by Django 4.1.3 on 2022-12-17 22:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=50)),
                ('cuerpo', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='media')),
                ('categoria', models.CharField(choices=[('FUTBOL', 'Futbol'), ('JUEGOS', 'Juegos'), ('VIAJES', 'Viajes'), ('SALUD', 'Salud'), ('EVENTOS', 'Eveentos'), ('VARIOS', 'Varios')], default='VARIOS', max_length=9)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
