# Generated by Django 4.1.3 on 2022-12-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('Futbol', 'Futbol'), ('Juegos', 'Juegos'), ('Viajes', 'Viajes'), ('Salud', 'Salud'), ('Eventos', 'Eveentos'), ('Varios', 'Varios')], default='VARIOS', max_length=9),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
